### ISSUE TITLE
Reading problems Vzum

### ISSUE THREAD

**Issue by Laky25cz** [JanPalasek/ulozto-captcha-breaker#3]
Hello, Im trying to download some apps with the program i use and the program uses this script, There are some problems its not as good as before now it gets very easily broken and it can't read that good, please fix that.

**Comment by JanPalasek** [comment]
Hi,

can u tell me how exactly you use the ulozto-captcha-breaker? Is it via vzum, or some other method? How did you find out that it's worse than it used to be?

**Comment by ghost** [comment]
Im using a program called vzum It says it can auto-read captcha codes using this script (its movie downloader) I had it 1 year ago and it worked perfectly, Now When Ulož.to Updated, And this script probably too, Same with the Program It started Breaking (It cant read Captcha codes because error 50), or It tries to read but unsuccessfully, And i need to type it myself, So it probably needs an update. http://vzum.8u.cz/ It worked nicely before but after recent updates, it just won't read the codes or it reads the code unsuccessfully. I have 15 parts and only 4 Of them are successfully read by the script.

**Comment by JanPalasek** [comment]
Can u enclose the vzum log?

**Comment by ghost** [comment]
What Kind of log do you mean? The log Under The Start Button or The Application log?  I really can't get to the app log because I'm not an owner (Ig i can use some kind of program) but I can give you the log under Start Button.

**Comment by JanPalasek** [comment]
The log under the start button.

**Comment by JanPalasek** [comment]
I got to try vzum, I tried to download using three parts, it worked and produced the following log:
```
12:23:31 | Vžum vás vítá! Návod k použití na http://vzum.8u.cz/
12:23:31 | ...
12:23:31 | Po poslední aktualizaci by Vžum mělo méně padat.
12:23:31 | ...
12:24:26 | Kliknuto na tlačítko start
12:24:26 | Vytvořena dočasná složka C:\Users\janpa\Videos\the-mandalorian-s02e01-chapter-9-1080p-en-5-1-sub-en-cz-ell.mkv_3parts
12:24:26 | Spuštěno vlákno stahování pro část 0
12:24:26 | Vlákno 0 vytváří vlastní dočasný soubor
12:24:26 | Vlákno 0 žádá Ulož.to o soubor, pokus 1
12:24:26 | Vlákno 0 se pokouší přečíst captcha, pokus 1
12:24:28 | Vláknu 0 nebyl přijat captcha kód
12:24:28 | Vlákno 0 žádá Ulož.to o soubor, pokus 2
12:24:29 | Vlákno 0 se pokouší přečíst captcha, pokus 2
12:24:30 | Vláknu 0 nebyl přijat captcha kód
12:24:30 | Vlákno 0 žádá Ulož.to o soubor, pokus 3
12:24:30 | Vlákno 0 se pokouší přečíst captcha, pokus 3
12:24:31 | Vláknu 0 úspěšně přijat captcha kód
12:24:31 | Započat příjem dat vláknem 0
12:24:31 | Spuštěno vlákno stahování pro část 1
12:24:31 | Mezi každými dvěma vlákny minutu čekám...
12:24:31 | Vlákno 1 vytváří vlastní dočasný soubor
12:24:31 | Vlákno 1 žádá Ulož.to o soubor, pokus 1
12:24:32 | Vlákno 1 se pokouší přečíst captcha, pokus 1
12:24:33 | Vláknu 1 nebyl přijat captcha kód
12:24:33 | Vlákno 1 žádá Ulož.to o soubor, pokus 2
12:24:33 | Vlákno 1 se pokouší přečíst captcha, pokus 2
12:24:34 | Vláknu 1 úspěšně přijat captcha kód
12:24:35 | Započat příjem dat vláknem 1
12:25:31 | Spuštěno vlákno stahování pro část 2
12:25:31 | Vlákno 2 vytváří vlastní dočasný soubor
12:25:31 | Vlákno 2 žádá Ulož.to o soubor, pokus 1
12:25:32 | Vlákno 2 se pokouší přečíst captcha, pokus 1
12:25:33 | Vlákno 2 bylo odmítnuto a musí čekat
12:26:33 | Vlákno 2 žádá Ulož.to o soubor, pokus 2
12:26:34 | Vlákno 2 se pokouší přečíst captcha, pokus 2
12:26:37 | Vláknu 2 úspěšně přijat captcha kód
12:26:39 | Započat příjem dat vláknem 2
```

I also tried the captcha reading not using vzum and it worked as well. Captchas are still the same, the neural network reading it is still the same. It hasn't been modified since April.

**Comment by ghost** [comment]
Hello, Tried it and it worked okay, But why did it not work ok the other days? Like 2 days ago i needed to enter all the captcha codes myself and there were errors like an entire week and now it seems ''okay''

**Comment by JanPalasek** [comment]
Ulozto has added new layers of protection, although I don't know the exact details like what and where, except for the fact that download threads now start with delay to bypass that. 
However, I'm fairly positive that the bug didn't appear due to captcha reading. It has approximately 80% accuracy, so it will work well until they decide to change the captchas entirely.

I'll close the issue. If you encounter any other problem, create a new issue or contact Vzum creator.

**Comment by JanPalasek** [comment]
@Laky25cz I contacted Vzum's author, he's aware of this issue and will solve it when he has time.
